replace the grid extension in this package with the one in pystac
stactools-packages/naip pull request #37
Opened 2023-04-18 14:47 UTC by philvarner

**Related Issue(s):**

- n/a

**Proposed Changes:**

1. replace the the GridExtension class in this package with the GridExtension class in pystac

**PR Checklist:**

- [X] I have added my changes to the [CHANGELOG](https://github.com/stactools/naip/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

2023-04-18 21:12 UTC, gadomski approved these changes

2023-04-18 21:14 UTC, gadomski requested changes
Even though it's not required b/c of transitive dependencies, we should explicitly floor `pystac >= 1.5` in the `setup.cfg` for this package, to be explicit that we need `pystac` and the grid extension (which was added in v1.5.0).

2023-04-19 14:11 UTC, philvarner commented
> Even though it's not required b/c of transitive dependencies, we should explicitly floor `pystac >= 1.5` in the `setup.cfg` for this package, to be explicit that we need `pystac` and the grid extension (which was added in v1.5.0).

stactools >= 0.4.3 requires pystac[validation] >= 1.6.1

2023-04-19 14:13 UTC, gadomski commented
> stactools >= 0.4.3 requires pystac[validation] >= 1.6.1

Right, but since we explicitly import and use `pystac` it (IMO) is best practice to add `pystac` to `install_requires` as well. I recognize this practice isn't followed everywhere, but given an opportunity to do it, we should (again, IMO).

2023-04-19 14:27 UTC, merged